### PR TITLE
Feature/28 Promoter Db skeleton UI

### PR DESCRIPTION
**Pull request by vidhya-metacell**

### CODE REVIEW

**Review by lrebscher — APPROVED** [review]
very nice 👍 
 
Minor thing: I would like to keep "Available Results" outside of the scroll container. 

If a user clicks on "Load More" when she's at the bottom of the container, she won't see how many results are now displayed because it's unlikely that we would reset the scroll position to 0.  

But I leave this up for discussion (fyi @ddelpiano )

**Comment by vidhya-metacell** [comment]
@lrebscher should i move the available results outside the container or are you waiting for @ddelpiano response?

**Comment by lrebscher** [comment]
let's wait for Dario's response!

**Comment by ddelpiano** [comment]
> very nice 
> 
> Minor thing: I would like to keep "Available Results" outside of the scroll container.
> 
> If a user clicks on "Load More" when she's at the bottom of the container, she won't see how many results are now displayed because it's unlikely that we would reset the scroll position to 0.
> 
> But I leave this up for discussion (fyi @ddelpiano )

That's fine for me 👍🏽

**Pull request merged**
