### PR TITLE
YALE-27 feat: Add context menu to CPHATE

### PR DESCRIPTION
**Pull request by afonsobspinto**
Requires: https://github.com/MetaCell/geppetto-meta/pull/515

Closes https://metacell.atlassian.net/browse/YALE-27

https://github.com/MetaCell/geppetto-NeuroSCAN/assets/19196034/0309265c-170b-476b-825d-252d72e59696

### CODE REVIEW

**Comment by afonsobspinto** [comment]
@zsinnema I'm adding you as a reviewer while still a draft because on my side, at least until I hear back from you :stuck_out_tongue: , the only thing missing is to update the geppetto version to a new one yet to be released. I already talked with @enicolasgomez about it.

**Comment by zsinnema** [comment]
@afonsobspinto why do we need a new geppetto version? and will this version be a patched one of the currently used one?

**Comment by afonsobspinto** [comment]
The patched version:
- wouldn't trigger the onSelection callback for right clicks
- was not sending the mouse coordinates on the callback
- had bug where the selection (only on selection, hovering was correct) was not working properly for devices with window.devicePixelRatio != 1

The new version will be on top of the patched one yes

**Comment by zsinnema** [comment]
@afonsobspinto lgtm, waiting for the new geppetto. Any idea when it will be released?

**Comment by afonsobspinto** [comment]
Thanks :+1: 
Sometime this week depending on @enicolasgomez availability

**Pull request merged**
