### PR TITLE
#208 chore: fixes issue search errors on pre neuron synapses filter

### PR DESCRIPTION
**Pull request by zsinnema**

### CODE REVIEW

**Review by ddelpiano — CHANGES_REQUESTED** [review]
@zsinnema the filtering with the old code works fine for me, with this new fix it does not anymore.

**Review by ddelpiano — CHANGES_REQUESTED** [review]
@zsinnema the filter still does not work

**Comment by zsinnema** [comment]
@ddelpiano just to double check with you: you are running the client against a local strapi server? Right? Because I did in this PR some changes in the backend and they are not on the yale.metacell.us server yet

**Review by ddelpiano — APPROVED** [review]
@zsinnema this looks good to me, I pushed a change in the filter component to fix a broken state when removing all the search term from the search input text, let me know if that is ok and we can merge this.

**Pull request merged**
